### ISSUE TITLE
Update depricated ::set-output command

### ISSUE THREAD

**Issue by cdhunt** [autero1/action-gotestsum#28]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

>Action authors who are using the toolkit should update the `@actions/core package` to `v1.10.0` or greater to get the updated `saveState` and `setOutput` functions.

**Comment by zalenskivolt** [comment]
> Action and workflow authors who are using save-state or set-output via stdout should update to use the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).
```shell
run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

**Comment by autero1** [comment]
The associated PR was merged, so this is now fixed. Also, Node was upgraded to v16, so a new major release is out: https://github.com/autero1/action-gotestsum/releases/tag/v2.0.0
